baseURL = 'https://1917dc.github.io'
languageCode = 'pt-br'
title = 'Hugo Sputnik'
theme = 'hugo-sputnik'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 20

[[menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 30

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 40


[taxonomies]
  tag = 'tags'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    lineAnchors = ""
    lineNoStart = 1
    tabWidth = 4

[params]
  [params.bio]
    name = 'Author Name'
    theme = 'Hugo Sputnik'
    startYear = '2024'
    
  [params.social]
    github = ''
    lastfm = ''
    letterboxd = ''
    instagram = ''

  [params.contact]
    email = 'mailto:your-email@example.com'

  [params.logo]
    image = '/logo.svg'
  
  [params.favicon]
    icon = '/favicon.svg'

[caches]
  [caches.images]
    dir = ':cacheDir/images'